name: KeyAllX
version: 0.0.7
main: studio.xstream.keyallx.KeyAllX
api-version: '1.20'
author: XStreamStudio
softdepend:
  - PlaceholderAPI
commands:
  keyallx:
    description: Reload the plugin with /keyallx reload
    permission: op

  reset-timer:
    usage: /reset-timer
    description: Reset the keyall timer
    permission: op
